apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
  namespace: kube-system
spec:
  containers:
    - name: nginx-container
      image: nginx  # full path, if you're not using registry other than Docker Hub
