apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: reqs-limits-pod
  name: attempt-reqs-limits-pod
  namespace: one
spec:
  containers:
  - image: nginx
    resources:
      requests:
        memory: "1Gi"
        cpu: "0.5"
      limits:
        memory: "2Gi"
        cpu: "1"
    name: reqs-limits
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# Create a pod with resource requests cpu=0.5, memory=1Gi and limits cpu=1, memory=2Gi in namespace one
