apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: reqs-limits-pod
  name: attempt-reqs-limits-pod
  namespace: one
spec:
  containers:
  - image: nginx
    resources:
      requests:
        memory: "3Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "3"
    name: reqs-limits
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# Attempt to create a pod with resource requests cpu=2, memory=3Gi and limits cpu=3, memory=4Gi in namespace one
# Error from server (Forbidden): error when creating "attempt-reqs-limits-pod.yaml": pods "attempt-reqs-limits-pod" is forbidden: failed quota: resourcequota-ns-one: must specify limits.cpu for: reqs-limits-pod; requests.cpu for: reqs-limits-pod
