apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-pod-with-pvc
  name: busybox-pod-with-pvc
spec:
  containers:
  - image: busybox
    name: busybox-pod-with-pvc
    args: ["sleep", "3600"]
    volumeMounts:
    - name: data
      mountPath: /etc/foo
  restartPolicy: Never

  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mypvc


# Create a busybox pod with command 'sleep 3600', save it on pod.yaml. Mount the PersistentVolumeClaim to '/etc/foo'. Connect to the 'busybox' pod, and copy the '/etc/passwd' file to '/etc/foo/passwd'

