apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-pod-local-cp
  name: busybox-pod-local-cp
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: busybox-pod-local-cp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
