apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-two-containers-pod
  name: busybox-two-containers-pod
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: busybox-two-containers-pod-1
    volumeMounts:
    - name: storage
      mountPath: /etc/foo

  - args:
    - sleep
    - "3600"
    image: busybox
    name: busybox-two-containers-pod-2
    volumeMounts:
    - name: storage
      mountPath: /etc/foo

  restartPolicy: Never

  volumes:
  - name: storage
    emptyDir: {}
