apiVersion: v1
kind: Pod
metadata:
  name: consumer
  namespace: secret-ops
spec:
  restartPolicy: Never
  containers:
    - name: consumer-container
      image: nginx
      env:
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: ext-service-secret
            key: API_KEY

# Consuming the Secret. Create a Pod named 'consumer' with the image 'nginx' in the namespace 'secret-ops' and consume the Secret as an environment variable. Then, open an interactive shell to the Pod, and print all environment variables.

