apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consumer
  name: consumer
  namespace: secret-ops
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
  containers:
  - image: nginx
    name: consumer-container
    volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: "/var/app"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

# Create a Pod named 'consumer' with the image 'nginx' in the namespace 'secret-ops', and consume the Secret as Volume. Mount the Secret as Volume to the path /var/app with read-only access. Open an interactive shell to the Pod, and render the contents of the file.
