apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      envFrom:
      - configMapRef:
          name: game-config

#     env:
#       - name: GAME_PROPERTIES
#         valueFrom:
#           configMapKeyRef:
#             # The ConfigMap containing the value you want to assign to GAME_PROPERTIES
#             name: game-config
#             # Specify the key associated with the value
#             key: enemies
   
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: game-config
#       optional: true # mark the source ConfigMap as optional
  restartPolicy: Never

