apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: one
spec:
  limits:
  - default:
      memory: 500Mi
    defaultRequest:
      memory: 100Mi
    max:
      memory: 512Mi
    type: Container

# Create a namespace named limitrange with a LimitRange that limits pod memory to a max of 500Mi and min of 100Mi
