apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: reqs-limits-pod
  name: limitsrange-reqs-limits-pod
  namespace: one
spec:
  containers:
  - image: nginx
    resources:
      requests:
        memory: "250Mi"
    name: limitsrange-reqs-limits
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# Create an nginx pod that requests 250Mi of memory in the limitrange namespace
