apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: my-httpd
    meta.helm.sh/release-namespace: app
  creationTimestamp: "2024-04-27T23:01:50Z"
  labels:
    app.kubernetes.io/instance: my-httpd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: httpd
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: httpd-0.1.0
  name: my-httpd
  namespace: app
  resourceVersion: "154851"
  uid: 4bd2c1d0-ef57-4b9d-a2c8-1316faa4902f
spec:
  clusterIP: 10.43.21.155
  clusterIPs:
  - 10.43.21.155
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31586
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: my-httpd
    app.kubernetes.io/name: httpd
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
