apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nginx-pod-exposed
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
#   run: nginx-pod-exposed
    k8s-app: traefik-ingress-lb
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
#   run: nginx-pod-exposed
    k8s-app: traefik-ingress-lb
  name: nginx-pod-exposed
spec:
  containers:
  - image: nginx
    name: nginx-pod-exposed
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
