apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"name":"nginx-pod-exposed","namespace":"app"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"run":"nginx-pod-exposed"}},"status":{"loadBalancer":{}}}
  creationTimestamp: "2024-04-24T02:25:43Z"
  name: nginx-pod-exposed
  namespace: app
  resourceVersion: "128207"
  uid: 97872481-076c-4564-a795-b637dfa71129
spec:
  clusterIP: 10.43.41.96
  clusterIPs:
  - 10.43.41.96
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-pod-exposed
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
