apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-refs-cm
spec:
  containers:
    - name: nginx-container
      image: nginx
#     command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: var6
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign 
              name: anotherone
              # Specify the key associated with the value
              key: var6
        - name: var7
          valueFrom:
            configMapKeyRef:
              name: anotherone
              key: var7
  restartPolicy: Never
