# Create a busybox pod with command 'sleep 3600', save it on pod.yaml. Mount the PersistentVolumeClaim to '/etc/foo'. Connect to the 'busybox' pod, and copy the '/etc/passwd' file to '/etc/foo/passwd'

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod2
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: pod
    volumeMounts:
      - mountPath: "/etc/foo"
        name: storage

  restartPolicy: Never

  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: mypvc
