apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: reqs-limits-pod
  name: reqs-limits-pod
spec:
  containers:
  - image: nginx
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    name: reqs-limits
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# Create an nginx pod with requests cpu=100m,memory=256Mi and limits cpu=200m,memory=512Mi
