apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: resourcequota-ns-one
  namespace: one
spec: 
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi

# Create ResourceQuota in namespace one with hard requests cpu=1, memory=1Gi and hard limits cpu=2, memory=2Gi

# Usage:
# kubectl create quota NAME [--hard=key1=value1,key2=value2] [--scopes=Scope1,Scope2] [--dry-run=server|client|none]
#[options]
