apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sec-context-pod
  name: sec-context-pod
spec:
# securityContext:
#   runAsUser: 101
  containers:
  - image: nginx
    name: sec-context-pod
    securityContext:
      capabilities: 
        add: ["NET_ADMIN", "SYS_TIME"]

