apiVersion: v1
kind: Pod
metadata:
  name: secret-in-volume-pod
spec:
  restartPolicy: Never
  volumes:
    - name: secret-volume
      secret:
        secretName: mysecret2
  containers:
    - name: secret-in-volume
      image: nginx
      command:
        - ls
        - "-l"
        - "/etc/foo"
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/foo"

# Create an nginx pod that mounts the secret mysecret2 in a volume on path /etc/foo
