apiVersion: v1
kind: Pod
metadata:
  name: secret-in-env-var-pod
spec:
  restartPolicy: Never
  containers:
    - name: secret-in-env-var
      image: nginx
      env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret2
            key: username
#     command:
#       - /bin/sh
#       - "-c"
#       - "echo $SECRET_USERNAME"

# Delete the pod you just created and mount the variable 'username' from secret mysecret2 onto a new nginx pod in env variable called 'USERNAME'
