apiVersion: v1
kind: Pod
metadata:
  name: troubleshooting-pod 
spec:
  containers:
  - name: troubleshooter
    image: busybox
    # Just spin & wait forever
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
