apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: newdemo
  name: newdemo
  namespace: kubernetes-dashboard
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: newdemo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: newdemo
    spec:
      containers:
      - image: cloudnatived/demo:hello
        imagePullPolicy: IfNotPresent
        name: demo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
